name: fast-maas-api
title: fast-maas-api
version: '0.0.1'
summary: A community tool to retrieve your machines in a fast way
description: |
  fast-maas-api is a community tool to access your MAAS database and extract the machines list and details
  in an incredibly fast way. 
  In particular, a webservice is exposed at port 1337 and you can use the exposed endpoints to retrieve the data you 
  need.
base: core22
grade: devel
confinement: strict

apps:
  fast-maas-api:
    command: start_snap.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - network
      - network-bind

parts:
  fast-maas-api:
    plugin: dump
    source: .
    organize:
      bin/start_snap.sh: /
      target/quarkus-app/: /quarkus-app/
    stage-packages:
      - openjdk-11-jre
    override-stage: |
      snapcraftctl stage
      chmod +xr start_snap.sh
    prime:
    - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts
    - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
