name: fast-maas-api
title: fast-maas-api
version: '0.0.1'
summary: A community tool to retrieve your machines in a fast way
description: |
  fast-maas-api is a community tool to access your MAAS database and extract the machines list and details
  in an incredibly fast way. 
  In particular, a webservice is exposed at port 1337 and you can use the exposed endpoints to retrieve the data you 
  need.
base: core18
grade: devel
confinement: strict

apps:
  fast-maas-api:
    command: start_snap.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - network
      - network-bind

parts:
  fast-maas-api:
    plugin: maven
    source: .
    source-type: local
    build-packages:
      - maven
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jre
    override-build: |
      ./mvnw clean package -DskipTests
      cp bin/start_snap.sh $SNAPCRAFT_PART_INSTALL/
      cp -R target/quarkus-app/ $SNAPCRAFT_PART_INSTALL/
      chmod +x $SNAPCRAFT_PART_INSTALL/start_snap.sh
